CREATE TABLE cities (
                        city_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        name_of_city VARCHAR(255) NOT NULL,
                        cultural_heritage VARCHAR(255) NOT NULL,
                        city_prefix VARCHAR(255) NOT NULL UNIQUE
);

CREATE TABLE gastronomies (
                              gastronome_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              name_of_gastronome VARCHAR(255) NOT NULL,
                              schedule VARCHAR(255),
                              longitude DOUBLE PRECISION NOT NULL,
                              latitude DOUBLE PRECISION NOT NULL,
                              type_of_gastronome VARCHAR(255) CHECK (type_of_gastronome IN ('CAFFE', 'RESTAURANT', 'HOTEL')) NOT NULL,
                              city_id BIGINT REFERENCES cities(city_id)
);

CREATE TABLE reservations (
                              reservation_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                              gastronome_id BIGINT REFERENCES gastronomies(gastronome_id),
                              reservation_date VARCHAR(255) NOT NULL,
                              phone_number VARCHAR(255) NOT NULL,
                              number_of_people INT NOT NULL,
                              special_requests VARCHAR(255),
                              status VARCHAR(255) CHECK (status IN ('ACTIVE', 'CANCELLED', 'COMPLETED')) NOT NULL
);

CREATE TABLE trips (
                       id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       num_of_days INT,
                       city_ids JSONB,
                       types_of_gastronome JSONB
);

CREATE TABLE trip_cities (
                             trip_id BIGINT REFERENCES trips(id),
                             city_id BIGINT,
                             PRIMARY KEY (trip_id, city_id)
);

CREATE TABLE users (
                       user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                       first_name VARCHAR(255) NOT NULL,
                       last_name VARCHAR(255) NOT NULL,
                       email VARCHAR(255) NOT NULL,
                       password VARCHAR(255) NOT NULL,
                       user_role VARCHAR(255) CHECK (user_role IN ('USER', 'ADMIN')) NOT NULL
);
